name: estuda_ai_novo
description: Planejador de Estudos - Organize suas matérias e acompanhe seu progresso
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Adicione esta seção para incluir o ícone nos assets
  assets:
    - assets/icons/
    - assets/images/

# Configuração do ícone do app
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#5AB2E8"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

  # Configurações específicas do Android
  android_gravity: "center"
  android_adaptive_icon_foreground: "assets/icons/app_icon.png"

  # Remove o banner de debug no ícone
  remove_alpha_ios: true
